# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Serge Laguerre
title: Web Developer
email: serge.laguerre@outlook.com
# website: www.github.com/sproogen/resume-theme

# Social links
twitter_username: Serginho_kun
github_username:  SerginhoKun
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
# linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Serge and I'm a french web developer. I am currently an expatriate in Beijing and I would like to relocate preferably in North America or in Europe.
  I have worked in several projects with different programming languages and framework, my biggest strenghts are adaptability and dedication in my work.
#  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in new technologies and software engineering some of my other interests and hobbies are:
   - Soccer
   - Gaming
   - Science-fiction
#   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
